# Generated by Django 4.0.4 on 2022-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0002_rename_family_appfamily'),
    ]

    operations = [
        migrations.AddField(
            model_name='appfamily',
            name='dni',
            field=models.PositiveIntegerField(default=35152478),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appfamily',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
