# Generated by Django 4.0.4 on 2022-05-26 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('families', '0003_appfamily_dni_alter_appfamily_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appfamily',
            name='dni',
        ),
    ]
